import { DASHBOARD_MODULE_NAME } from './constants'

export const INIT_DASHBOARD_DATA = `${DASHBOARD_MODULE_NAME}/INIT_DASHBOARD_DATA`
export const RESET_DASHBOARD_DATA = `${DASHBOARD_MODULE_NAME}/RESET_DASHBOARD_DATA`
export const SET_LAST_ACTIVITY = `${DASHBOARD_MODULE_NAME}/SET_LAST_ACTIVITY`