
export enum ErrorCodes {

    // Commons
    UNKNOWN = 100,
    NOT_IMPLEMENTED = 101,
    BROKERCODE_UNKNOWN = 102,
    BROKER_ADAPTER_NOT_FOUND = 103,
    MODULE_INVALID = 104,
    
    // Cache
    ENTITY_NOT_PROVIDED = 600,
    
    // Frequency
    FREQUENCY_NOT_FOUND = 400,

    // Strategy
    STRATEGY_NOT_FOUND = 450,

    // Broker
    BROKER_ACCOUNT_USERACCOUNT_REQUIRED = 200,
    BROKER_ACCOUNT_NAME_REQUIRED = 201,
    BROKER_ACCOUNT_BROKERCODE_REQUIRED = 202,

    // User Account
    ACCOUNT_IS_SIMULATION = 500,
    ACCOUNT_HAS_SIMULATION = 501,

    // Stock
    LAST_PRICE_NOT_FOUND = 550,

    // Stock Tracker
    STOCK_TRACKER_SYMBOL_NOT_FOUND = 650,
    STOCK_TRACKER_ACCOUNT_NOT_FOUND = 651,
    STOCK_TRACKER_STRATEGY_NOT_FOUND = 652,
    STOCK_TRACKER_STATUS_NOT_FOUND = 653,

    // Clear
    IS_NOT_VALID_CLEAR_ACCOUNT = 700,
    EXCHANGEORDERTYPE_INVALID = 701,
    EXCHANGEORDERSIDE_INVALID = 702,
    ORDERSTATUS_INVALID = 703,
    CLEAR_CREDENTIALS_FAIL = 704
    
}