import { BALANCE_MODULE_NAME } from './constants'

export const INIT_BALANCE_SHEET_HISTORY = `${BALANCE_MODULE_NAME}/SELECT_BALANCE_SHEET_HISTORY`
export const SELECT_BALANCE_SHEET_HISTORY = `${BALANCE_MODULE_NAME}/SELECT_BALANCE_SHEET_HISTORY`
export const APPEND_BALANCE_SHEET_HISTORIES = `${BALANCE_MODULE_NAME}/APPEND_BALANCE_SHEET_HISTORIES`
export const CLEAR_BALANCE_SHEET_HISTORIES = `${BALANCE_MODULE_NAME}/CLEAR_BALANCE_SHEET_HISTORIES`