import { STOCK_TRACKER_MODULE_NAME } from './constants'

export const INIT_STOCK_TRACKER_MODULE = `${STOCK_TRACKER_MODULE_NAME}/INIT_STOCK_TRACKER_MODULE`
export const SELECT_STOCK_TRACKER = `${STOCK_TRACKER_MODULE_NAME}/SELECT_STOCK_TRACKER`
export const UPDATE_MAIN_STOCK_TRACKER = `${STOCK_TRACKER_MODULE_NAME}/UPDATE_MAIN_STOCK_TRACKER`
export const UPDATE_SELECTED_STOCK_TRACKER = `${STOCK_TRACKER_MODULE_NAME}/UPDATE_SELECTED_STOCK_TRACKER`
export const SELECT_STOCK_TRACKER_TO_UPDATE = `${STOCK_TRACKER_MODULE_NAME}/SELECT_STOCK_TRACKER_TO_UPDATE`
export const APPEND_STOCK_TRACKERS = `${STOCK_TRACKER_MODULE_NAME}/APPEND_STOCK_TRACKERS`
export const REMOVE_STOCK_TRACKERS = `${STOCK_TRACKER_MODULE_NAME}/REMOVE_STOCK_TRACKERS`
export const APPEND_STOCK_TRACKER_ACTIVITIES = `${STOCK_TRACKER_MODULE_NAME}/APPEND_STOCK_TRACKER_ACTIVITIES`
export const CLEAR_STOCK_TRACKER_PREVIEW = `${STOCK_TRACKER_MODULE_NAME}/CLEAR_STOCK_TRACKER_PREVIEW`
export const REGISTER_STOCK_TRACKER_BALANCE = `${STOCK_TRACKER_MODULE_NAME}/REGISTER_STOCK_TRACKER_BALANCE`
export const RESET_STOCK_TRACKER_MODULE = `${STOCK_TRACKER_MODULE_NAME}/RESET_STOCK_TRACKER_MODULE`
export const PREPATE_STOCK_TRACKER_TO_CREATE = `${STOCK_TRACKER_MODULE_NAME}/PREPATE_STOCK_TRACKER_TO_CREATE`
