import { MESSAGE_MODULE_NAME } from './constants'

export const SHOW_SUCCESS_MESSAGE = `${MESSAGE_MODULE_NAME}/SHOW_SUCCESS_MESSAGE`
export const SHOW_ERROR_MESSAGE = `${MESSAGE_MODULE_NAME}/SHOW_ERROR_MESSAGE`
export const SHOW_CONFIRMATION_MESSAGE = `${MESSAGE_MODULE_NAME}/SHOW_CONFIRMATION_MESSAGE`
export const CLOSE_MESSAGE = `${MESSAGE_MODULE_NAME}/CLOSE_MESSAGE`