import { BROKER_MODULE_NAME } from './constants'

export const APPEND_BROKER_ACCOUNTS = `${BROKER_MODULE_NAME}/APPEND_BROKER_ACCOUNTS`
export const SELECT_BROKER_ACCOUNT_TO_UPDATE = `${BROKER_MODULE_NAME}/SELECT_BROKER_ACCOUNT_TO_UPDATE`
export const PREPATE_BROKER_ACCOUNT_TO_CREATE = `${BROKER_MODULE_NAME}/PREPATE_BROKER_ACCOUNT_TO_CREATE`
export const UPDATE_SELECTED_BROKER_ACCOUNT = `${BROKER_MODULE_NAME}/UPDATE_SELECTED_BROKER_ACCOUNT`
export const UPDATE_SELECTED_EXTRA_DATA = `${BROKER_MODULE_NAME}/UPDATE_SELECTED_EXTRA_DATA`
export const RESET_BROKER_ACCOUNT_MODULE = `${BROKER_MODULE_NAME}/RESET_BROKER_ACCOUNT_MODULE`