import { SIGNIN_MODULE_NAME } from './constants'

export const REGISTER_AUTHENTICATED_USER = `${SIGNIN_MODULE_NAME}/REGISTER_AUTHENTICATED_USER`
export const REGISTER_USER_EMAIL = `${SIGNIN_MODULE_NAME}/REGISTER_USER_EMAIL`
export const REGISTER_USER_PASSWORD = `${SIGNIN_MODULE_NAME}/REGISTER_USER_PASSWORD`
export const REGISTER_USER_KEEPSESSION = `${SIGNIN_MODULE_NAME}/REGISTER_USER_KEEPSESSION`
export const RESET_SIGNIN_FORM = `${SIGNIN_MODULE_NAME}/RESET_SIGNIN_FORM`
export const SIGNOUT = `${SIGNIN_MODULE_NAME}/SIGNOUT`