import { ACTIVITY_MODULE_NAME } from './constants'

export const SELECT_ACTIVITY = `${ACTIVITY_MODULE_NAME}/SELECT_ACTIVITY`
export const APPEND_ACTIVITIES = `${ACTIVITY_MODULE_NAME}/APPEND_ACTIVITIES`
export const RESET_ACTIVITY_MODULE = `${ACTIVITY_MODULE_NAME}/RESET_ACTIVITY_MODULE`