export const MODULE_NAME = "Navigation"

export type Stacks = "auth" | "authFailure" | "app" | "welcome"

export enum Drawers {
    DASHBOARD = "DASHBOARD",
    INVESTIMENTS = "INVESTIMENTS",
    ANALYSIS = "ANALYSIS",
    STATEMENTS = "STATEMENTS",
    ACTIVITIES = "ACTIVITIES",
    BROKERS = "BROKERS",
    SETTINGS = "SETTINGS",
    PROFILE = "PROFILE",
}

export enum Routes {
    SPLASH = "SPLASH",
    TOUR = "TOUR",
    SIGN_IN = "SIGN_IN",
    SIGN_UP = "SIGN_UP",
    AUTH_FAILURE = "AUTH_FAILURE",
    DASHBOARD = "DASHBOARD",
    INVESTIMENT = "INVESTIMENT",
    ACTIVITY_LIST = "ACTIVITY_LIST",
    ACTIVITY_DETAIL = "ACTIVITY_DETAIL",
    INVESTIMENT_ANALYSIS = "INVESTIMENT_ANALYSIS",
    INVESTIMENT_ANALYSIS_DETAIL = "INVESTIMENT_ANALYSIS_DETAIL",
    INVESTIMENT_FILTER = "INVESTIMENT_FILTER",
    ADD_INVESTIMENT = "ADD_INVESTIMENT",
    STATEMENT = "STATEMENT",
    STATEMENT_DETAIL = "STATEMENT_DETAIL",
    STOCKTRACKER_PREVIEW = "STOCKTRACKER_PREVIEW",
    STOCKTRACKER_REVIEW = "STOCKTRACKER_REVIEW",
    STOCKTRACKER_FREQUENCY = "STOCKTRACKER_FREQUENCY",
    STOCKTRACKER_SETTING = "STOCKTRACKER_SETTING",
    STOCKTRACKER_STRATEGY = "STOCKTRACKER_STRATEGY",
    STOCKTRACKER_TRANSACTION = "STOCKTRACKER_TRANSACTION",
    STOCKTRACKER_WIZARD = "STOCKTRACKER_WIZARDE",
    BROKER_ACCOUNT_WIZARD = "BROKER_ACCOUNT_WIZARD",
    ADD_BROKER_ACCOUNT = "ADD_BROKER_ACCOUNT",
    SETTING = "SETTING",
    PROFILE = "PROFILE",
}
