import { ACCOUNT_MODULE_NAME } from './constants'

export const SELECT_ACCOUNT_TO_UPDATE = `${ACCOUNT_MODULE_NAME}/SELECT_ACCOUNT_TO_UPDATE`
export const CHANGE_ACCOUNT_DATA = `${ACCOUNT_MODULE_NAME}/CHANGE_ACCOUNT_DATA`
export const RESET_ACCOUNT_MODULE = `${ACCOUNT_MODULE_NAME}/RESET_ACCOUNT_MODULE`